tests updated to check station encoding error

diff --git a/.github/workflows/tests-docker.yml b/.github/workflows/tests-docker.yml
--- a/.github/workflows/tests-docker.yml
+++ b/.github/workflows/tests-docker.yml
@@ -63,6 +63,17 @@ jobs:
         python3 wis2box-ctl.py execute wis2box auth add-token -p wis2downloader github123 -y
         echo '{"topic": "origin/a/wis2/+/data/core/#"}' > test.json
         curl -X POST http://localhost/wis2downloader/subscriptions -H "Content-Type: application/json" -H "Authorization: Bearer github123" -d @test.json
+    - name: add Brazil wrongly encoded station data and check for error message
+      env:
+        STATION_METADATA: /data/wis2box/metadata/station/brazil.csv
+      run: |
+        output=$(python3 wis2box-ctl.py execute wis2box metadata station publish-collection --path $STATION_METADATA 2>&1)
+        status=$?
+        error = "Invalid utf-8 in station metadata file"
+        if [ $status -e 0 ]; then
+          exit 1
+        if [[ $output != *"$error"* ]]; then
+          exit 1
     - name: add CAP data, cap-publish 
       env:
         DISCOVERY_METADATA: /data/wis2box/metadata/discovery/int-wmo-test-cap.yml 
